system:
  mode: 0
  distribute: true
  amp_level: O0
  seed: 42
  log_interval: 200
  val_while_train: true
  drop_overflow_update: false
  training_step: LF_1
common:
  character_dict_path: null
  num_classes: 37
  max_text_len: 25
  infer_mode: false
  use_space_char: false
  batch_size: 192
  blank_at_last: false
  lower: true
model:
  type: rec
  transform: null
  resume: false
  backbone:
    name: rec_resnet45
    pretrained: false
    strides:
    - 2
    - 2
    - 2
    - 1
    - 1
  head:
    name: VisionLANHead
    n_layers: 3
    n_position: 256
    n_dim: 512
    max_text_length: 25
    training_step: LF_1
postprocess:
  character_dict_path: null
  use_space_char: false
  blank_at_last: false
  lower: true
metric:
  main_indicator: acc
  character_dict_path: null
  ignore_space: true
  print_flag: false
  device_num: 2
loss:
  mode: LF_1
  weight_res: 0.5
  weight_mas: 0.5
scheduler:
  scheduler: step_decay
  min_lr: 0.0
  lr: 0.0001
  decay_rate: 0.1
  decay_epochs: 6
  num_epochs: 8
  warmup_epochs: 0
optimizer:
  opt: adam
  weight_decay: 0.0
  nesterov: false
  grouping_strategy: visionlan
  training_step: LF_1
  lr:
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 0.0001
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-05
  loss_scale: 1.0
loss_scaler:
  type: static
  loss_scale: 512
train:
  ema: true
  ema_decay: 0.9999
  clip_norm: 20.0
  ckpt_save_dir: ./tmp_visionlan/LF_1
  dataset_sink_mode: true
  dataset:
    dataset_root: ./datasets
    data_dir: ./datasets/train
    sample_ratio: 0.001
    shuffle: true
    filter_max_len: true
    max_text_len: 25
    transform_pipeline:
    - DecodeImage:
        img_mode: BGR
        to_float32: false
    - VisionLANLabelEncode:
        max_text_len: 25
        character_dict_path: null
        use_space_char: false
        blank_at_last: false
        lower: true
    - SVTRRecAug:
        aug_type: 0
    - SVTRRecResizeImg:
        image_shape:
        - 64
        - 256
        padding: false
    - NormalizeImage:
        bgr_to_rgb: true
        is_hwc: true
        mean:
        - 0
        - 0
        - 0
        std:
        - 255.0
        - 255.0
        - 255.0
    - ToCHWImage: null
    output_columns:
    - image
    - label
    - label_res
    - label_sub
    - label_id
    - length
  loader:
    shuffle: true
    batch_size: 192
    drop_remainder: true
    max_rowsize: 12
    num_workers: 8
    prefetch_size: 192
eval:
  ckpt_load_path: ./tmp_visionlan/LF_1/best.ckpt
  dataset_sink_mode: false
  dataset:
    dataset_root: ./datasets
    data_dir: ./datasets/evaluation/Sumof6benchmarks
    sample_ratio: 1.0
    shuffle: false
    transform_pipeline:
    - DecodeImage:
        img_mode: BGR
        to_float32: false
    - VisionLANLabelEncode:
        max_text_len: 25
        character_dict_path: null
        use_space_char: false
        blank_at_last: false
        lower: true
    - SVTRRecResizeImg:
        image_shape:
        - 64
        - 256
        padding: false
    - NormalizeImage:
        bgr_to_rgb: true
        is_hwc: true
        mean:
        - 0
        - 0
        - 0
        std:
        - 255.0
        - 255.0
        - 255.0
    - ToCHWImage: null
    output_columns:
    - image
    - text_padded
    - length
    net_aux_input_column_index: []
  loader:
    shuffle: false
    batch_size: 64
    drop_remainder: false
    max_rowsize: 12
    num_workers: 8
